# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FunctionDemo' do
  inhibit_all_warnings!


  pod 'BaseLibs', :path => '../../BaseLibs'
pod 'mob_sharesdk'
pod 'mob_sharesdk/ShareSDKPlatforms/GooglePlus'
pod 'mob_sharesdk/ShareSDKPlatforms/Facebook'
pod 'mob_sharesdk/ShareSDKPlatforms/Twitter'
pod 'SSZipArchive'
end
